#!/bin/bash

# Session Start Hook - Shows roadmap status automatically
# This runs every time Claude Code starts in this project

echo ""
echo "🎯 MEAL PLANNING APP - PATH TO RETIREMENT"
echo "=========================================="
echo ""
echo "💰 ULTIMATE GOAL: \$100K MRR → \$3-5M Exit or \$50K/month Passive Income"
echo ""
echo "📍 CURRENT PHASE: Phase 1 - Make It Bulletproof (Months 1-2)"
echo ""
echo "🔥 TOP PRIORITIES THIS WEEK:"
echo "  1. Fix database schema issues (leftovers table)"
echo "  2. Add Stripe payment integration"
echo "  3. Update AI models to Claude 3.5 Haiku/Sonnet"
echo "  4. Build nutrition tracking system"
echo "  5. Create analytics dashboard"
echo ""
echo "💡 QUICK WINS (< 4 hours each):"
echo "  • Update AI models (2 hours) - Better + Cheaper"
echo "  • Add nutrition columns to database (2 hours)"
echo "  • Create pricing page component (3 hours)"
echo "  • Set up PostHog analytics (2 hours)"
echo ""
echo "📊 SUCCESS METRICS:"
echo "  Current: 0 paying customers, \$0 MRR"
echo "  Month 3 Target: 50 paying customers, \$500 MRR"
echo "  Month 12 Target: 2,000 paying customers, \$20K MRR"
echo ""
echo "📋 RECENT PROGRESS:"
git log -5 --oneline --decorate 2>/dev/null | head -5
echo ""
echo "🔍 Use '/roadmap' command for full details"
echo "📖 See IMPROVEMENT_ROADMAP.md for complete task list"
echo ""
echo "❓ What would you like to work on today?"
echo ""
