/**
 * 20 Unique Test User Personas
 * Each user has different behaviors, preferences, and usage patterns
 * to comprehensively test the app from different angles.
 */

export interface TestUser {
  id: number;
  name: string;
  persona: string;
  description: string;
  behaviors: string[];
  dietaryRestrictions: string[];
  householdSize: number;
  hasKids: boolean;
  techSavviness: 'low' | 'medium' | 'high';
  usagePattern: 'heavy' | 'moderate' | 'light';
  primaryFeatures: string[];
  edgeCases: string[];
}

export const testUsers: TestUser[] = [
  {
    id: 1,
    name: "Sarah - Busy Working Mom",
    persona: "busy_parent",
    description: "Works full-time, 2 kids, needs quick meal planning",
    behaviors: [
      "Rapid-fire adds meals to plan",
      "Uses generate week feature frequently",
      "Checks school menu daily",
      "Creates shopping lists on mobile",
    ],
    dietaryRestrictions: ["nut-free"],
    householdSize: 4,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "heavy",
    primaryFeatures: ["meal-planning", "school-menu", "shopping-list"],
    edgeCases: [
      "Double-clicks buttons rapidly",
      "Switches between weeks quickly",
      "Opens app on multiple devices",
    ],
  },
  {
    id: 2,
    name: "Mike - Recipe Collector",
    persona: "collector",
    description: "Imports recipes from many sources, rarely cooks",
    behaviors: [
      "Imports 50+ recipes via URL",
      "Uses AI import for complex sites",
      "Never plans meals",
      "Searches recipes frequently",
    ],
    dietaryRestrictions: [],
    householdSize: 1,
    hasKids: false,
    techSavviness: "high",
    usagePattern: "heavy",
    primaryFeatures: ["recipe-import", "recipe-search"],
    edgeCases: [
      "Imports same URL twice",
      "Imports broken/404 URLs",
      "Imports non-recipe pages",
      "Bulk imports many recipes quickly",
    ],
  },
  {
    id: 3,
    name: "Emma - Vegan Foodie",
    persona: "dietary_strict",
    description: "Strict vegan, very particular about ingredients",
    behaviors: [
      "Carefully reads all ingredients",
      "Edits imported recipes to remove non-vegan items",
      "Uses tags extensively",
      "Filters by cuisine type",
    ],
    dietaryRestrictions: ["vegan", "no-honey", "no-gelatin"],
    householdSize: 2,
    hasKids: false,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["recipes", "tags", "search"],
    edgeCases: [
      "Searches for empty tags",
      "Creates very long tag names",
      "Uses special characters in tags",
    ],
  },
  {
    id: 4,
    name: "Tom - Elderly User",
    persona: "accessibility",
    description: "70 years old, uses larger text, slower interactions",
    behaviors: [
      "Takes time between actions",
      "Re-reads confirmations",
      "Uses simple features only",
      "Rarely imports, types recipes manually",
    ],
    dietaryRestrictions: ["low-sodium", "diabetic-friendly"],
    householdSize: 2,
    hasKids: false,
    techSavviness: "low",
    usagePattern: "light",
    primaryFeatures: ["recipes", "meal-planning"],
    edgeCases: [
      "Session timeout during slow usage",
      "Forgets to save before navigating away",
      "Uses browser back button extensively",
    ],
  },
  {
    id: 5,
    name: "Alex - Power User Developer",
    persona: "power_user",
    description: "Tests edge cases intentionally, fast interactions",
    behaviors: [
      "Uses keyboard shortcuts",
      "Opens dev console",
      "Tests API rate limits",
      "Tries SQL injection in inputs",
    ],
    dietaryRestrictions: [],
    householdSize: 1,
    hasKids: false,
    techSavviness: "high",
    usagePattern: "heavy",
    primaryFeatures: ["all"],
    edgeCases: [
      "XSS attempts in text fields",
      "Very long inputs (10000+ chars)",
      "Unicode/emoji in all fields",
      "Concurrent requests",
      "Rapid page navigation",
    ],
  },
  {
    id: 6,
    name: "Maria - Large Family Organizer",
    persona: "large_family",
    description: "8 person household, complex meal planning needs",
    behaviors: [
      "Plans for large servings",
      "Uses leftovers tracking extensively",
      "Generates shopping lists for 8",
      "Coordinates multiple dietary needs",
    ],
    dietaryRestrictions: ["gluten-free-for-one", "dairy-free-for-another"],
    householdSize: 8,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "heavy",
    primaryFeatures: ["meal-planning", "leftovers", "shopping"],
    edgeCases: [
      "Servings > 20",
      "Many concurrent meal plan entries",
      "Large shopping lists (100+ items)",
    ],
  },
  {
    id: 7,
    name: "Jake - Mobile-Only User",
    persona: "mobile",
    description: "Only uses app on phone, often with poor connectivity",
    behaviors: [
      "Uses touch gestures",
      "Switches between portrait/landscape",
      "Loses connection mid-action",
      "Uses swipe navigation",
    ],
    dietaryRestrictions: [],
    householdSize: 3,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["shopping-list", "quick-view"],
    edgeCases: [
      "Offline mode behavior",
      "Slow 3G connection",
      "App backgrounded during save",
      "Pull-to-refresh spam",
    ],
  },
  {
    id: 8,
    name: "Linda - Restaurant Feature Tester",
    persona: "restaurant_user",
    description: "Uses restaurant features heavily for date nights",
    behaviors: [
      "Saves many restaurants",
      "Uses restaurant suggestions",
      "Scrapes restaurant menus",
      "Filters by cuisine and price",
    ],
    dietaryRestrictions: ["shellfish-allergy"],
    householdSize: 2,
    hasKids: false,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["restaurants"],
    edgeCases: [
      "Scrape closed restaurant sites",
      "Invalid restaurant URLs",
      "Restaurants with no menu online",
    ],
  },
  {
    id: 9,
    name: "Chris - School Menu Manager",
    persona: "school_parent",
    description: "Primary focus on school menu and lunch alternatives",
    behaviors: [
      "Imports school menus weekly",
      "Marks disliked items",
      "Plans alternative lunches",
      "Checks calendar view frequently",
    ],
    dietaryRestrictions: ["peanut-allergy"],
    householdSize: 4,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["school-menu", "lunch-alternatives", "bento"],
    edgeCases: [
      "Parse malformed school menu PDFs",
      "Dates in past/far future",
      "Overlapping menu entries",
    ],
  },
  {
    id: 10,
    name: "Pat - Minimalist User",
    persona: "minimalist",
    description: "Uses bare minimum features, values simplicity",
    behaviors: [
      "Only adds 5-10 recipes",
      "Manually plans one week at a time",
      "Never uses AI features",
      "Ignores most UI elements",
    ],
    dietaryRestrictions: [],
    householdSize: 1,
    hasKids: false,
    techSavviness: "low",
    usagePattern: "light",
    primaryFeatures: ["recipes", "meal-planning"],
    edgeCases: [
      "Empty states everywhere",
      "Minimal data in all forms",
      "No preferences set",
    ],
  },
  {
    id: 11,
    name: "Dana - International Cuisine Expert",
    persona: "international",
    description: "Cooks cuisines from around the world, uses Unicode",
    behaviors: [
      "Imports recipes in multiple languages",
      "Uses Unicode characters in names",
      "Has recipes with unusual ingredients",
      "Filters by many cuisine types",
    ],
    dietaryRestrictions: ["halal"],
    householdSize: 4,
    hasKids: true,
    techSavviness: "high",
    usagePattern: "moderate",
    primaryFeatures: ["recipes", "import"],
    edgeCases: [
      "Recipe names in Chinese/Arabic/Russian",
      "Right-to-left text",
      "Emojis in recipe names",
      "Unusual measurement units",
    ],
  },
  {
    id: 12,
    name: "Ryan - Batch Planner",
    persona: "batch",
    description: "Plans entire month at once, heavy leftovers user",
    behaviors: [
      "Generates multiple weeks at once",
      "Uses auto-generate exclusively",
      "Tracks all leftovers",
      "Never manually edits plans",
    ],
    dietaryRestrictions: [],
    householdSize: 2,
    hasKids: false,
    techSavviness: "medium",
    usagePattern: "heavy",
    primaryFeatures: ["auto-generate", "leftovers"],
    edgeCases: [
      "Generate 4 weeks in rapid succession",
      "Clear and regenerate frequently",
      "Very old leftover dates",
    ],
  },
  {
    id: 13,
    name: "Sam - New User Onboarding",
    persona: "new_user",
    description: "Brand new to app, follows onboarding exactly",
    behaviors: [
      "Reads all tooltips",
      "Follows onboarding tour",
      "Makes mistakes and undoes",
      "Explores every menu option",
    ],
    dietaryRestrictions: [],
    householdSize: 3,
    hasKids: false,
    techSavviness: "medium",
    usagePattern: "light",
    primaryFeatures: ["onboarding", "help"],
    edgeCases: [
      "Skip onboarding mid-way",
      "Restart onboarding",
      "Empty profile interactions",
    ],
  },
  {
    id: 14,
    name: "Kelly - Image-Heavy User",
    persona: "visual",
    description: "Imports recipes via images, takes photos of everything",
    behaviors: [
      "Uses image parsing for all recipes",
      "Uploads large images",
      "Expects images on all recipes",
      "Uses camera on mobile",
    ],
    dietaryRestrictions: ["keto"],
    householdSize: 2,
    hasKids: false,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["image-import", "camera"],
    edgeCases: [
      "Very large images (20MB+)",
      "Corrupted image files",
      "Non-image files with image extension",
      "Screenshots of recipes",
    ],
  },
  {
    id: 15,
    name: "Jordan - Frequent Editor",
    persona: "editor",
    description: "Constantly edits and updates existing content",
    behaviors: [
      "Edits recipes after import",
      "Changes meal plan daily",
      "Updates shopping list repeatedly",
      "Renames everything",
    ],
    dietaryRestrictions: [],
    householdSize: 4,
    hasKids: true,
    techSavviness: "high",
    usagePattern: "heavy",
    primaryFeatures: ["edit", "update"],
    edgeCases: [
      "Edit while another tab has same data",
      "Rapid edit/save cycles",
      "Undo after page refresh",
    ],
  },
  {
    id: 16,
    name: "Morgan - Multi-Tab User",
    persona: "multi_tab",
    description: "Opens app in 5+ tabs, works across them",
    behaviors: [
      "Compares recipes in tabs",
      "Edits in one tab, views in another",
      "Logs out in one tab",
      "Different weeks in different tabs",
    ],
    dietaryRestrictions: [],
    householdSize: 2,
    hasKids: false,
    techSavviness: "high",
    usagePattern: "heavy",
    primaryFeatures: ["all"],
    edgeCases: [
      "Data sync between tabs",
      "Session management across tabs",
      "Conflicting edits",
    ],
  },
  {
    id: 17,
    name: "Casey - Seasonal Planner",
    persona: "seasonal",
    description: "Uses seasonal features, plans around holidays",
    behaviors: [
      "Uses holiday planner",
      "Checks seasonal produce",
      "Plans special occasion meals",
      "Uses far future dates",
    ],
    dietaryRestrictions: [],
    householdSize: 6,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "moderate",
    primaryFeatures: ["seasonal", "holiday-planner"],
    edgeCases: [
      "Plans for dates 1 year out",
      "Dates across year boundaries",
      "Leap year handling",
    ],
  },
  {
    id: 18,
    name: "Riley - OAuth User",
    persona: "oauth",
    description: "Logs in via Google, tests auth edge cases",
    behaviors: [
      "Uses Google login only",
      "Revokes permissions occasionally",
      "Clears cookies frequently",
      "Uses incognito mode",
    ],
    dietaryRestrictions: [],
    householdSize: 1,
    hasKids: false,
    techSavviness: "high",
    usagePattern: "moderate",
    primaryFeatures: ["auth", "profile"],
    edgeCases: [
      "Login with expired token",
      "Multiple OAuth providers",
      "Profile sync issues",
    ],
  },
  {
    id: 19,
    name: "Avery - Shopping List Power User",
    persona: "shopping",
    description: "Lives in the shopping list, uses it daily at store",
    behaviors: [
      "Generates lists from plan",
      "Adds manual items constantly",
      "Checks off items rapidly",
      "Uses categories heavily",
    ],
    dietaryRestrictions: [],
    householdSize: 4,
    hasKids: true,
    techSavviness: "medium",
    usagePattern: "heavy",
    primaryFeatures: ["shopping-list"],
    edgeCases: [
      "500+ item shopping list",
      "Toggle all items rapidly",
      "Clear list mid-shopping",
    ],
  },
  {
    id: 20,
    name: "Quinn - Destructive Tester",
    persona: "destructive",
    description: "Tries to break things, tests delete/undo flows",
    behaviors: [
      "Deletes everything then undoes",
      "Clears all data frequently",
      "Tests cancel buttons",
      "Tries to delete while saving",
    ],
    dietaryRestrictions: [],
    householdSize: 1,
    hasKids: false,
    techSavviness: "high",
    usagePattern: "heavy",
    primaryFeatures: ["delete", "clear", "undo"],
    edgeCases: [
      "Delete last item in list",
      "Delete while offline",
      "Undo across page navigation",
      "Delete referenced items",
    ],
  },
];

export default testUsers;
